### ISSUE TITLE
CanaryLinks - Getting errors after recent update

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [bepvte/bd-addons#33]
```text
Canary 139400 (b9eb2af)
BetterDiscord 1.5.3-Hotfix
Host 0.0.285 OS X 10.15.7 (20.6.0)
```

Log:
```text
[2022-08-01 21:41:43.079][CONSOLE:ERROR] [Patcher] Could not fire after callback of default for Canary Links Cannot set property 'action' of undefined
TypeError: Cannot set property 'action' of undefined
    at CanaryLinks.channelCopyLink (betterdiscord://plugins/CanaryLinks.plugin.js:113:33)
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1665:51
    at k (https://canary.discord.com/assets/b80c549ddb5010be396c.js:3:392)
    at so (https://canary.discord.com/assets/5330781ffb195f47a020.js:5994:468)
    at Ko (https://canary.discord.com/assets/5330781ffb195f47a020.js:6004:218)
    at $s (https://canary.discord.com/assets/5330781ffb195f47a020.js:6047:84)
    at Gu (https://canary.discord.com/assets/5330781ffb195f47a020.js:6037:748)
    at wu (https://canary.discord.com/assets/5330781ffb195f47a020.js:6037:676)
    at Uu (https://canary.discord.com/assets/5330781ffb195f47a020.js:6037:539)
    at Au (https://canary.discord.com/assets/5330781ffb195f47a020.js:6034:164)
    at https://canary.discord.com/assets/5330781ffb195f47a020.js:5979:340
    at t.unstable_runWithPriority (https://canary.discord.com/assets/5330781ffb195f47a020.js:6168:828)
    at Ki (https://canary.discord.com/assets/5330781ffb195f47a020.js:5979:117)
    at qi (https://canary.discord.com/assets/5330781ffb195f47a020.js:5979:285)
    at Xi (https://canary.discord.com/assets/5330781ffb195f47a020.js:5979:220)
    at Tu (https://canary.discord.com/assets/5330781ffb195f47a020.js:6031:510)
    at Object.enqueueSetState (https://canary.discord.com/assets/5330781ffb195f47a020.js:5983:240)
    at t.h.setState (https://canary.discord.com/assets/5330781ffb195f47a020.js:6138:297)
    at https://canary.discord.com/assets/5330781ffb195f47a020.js:715:313
```

**Comment by bepvte** [comment]
Its harder for me to make a plugin that supports 3 versions at once, so I will fix this when it hits stable.
